package config

import (
	"github.com/NICEXAI/fstask"
	"github.com/NICEXAI/go2struct"
	"github.com/NICEXAI/lazy-go/internal/errorx"
	"github.com/NICEXAI/lazy-go/util"
	"github.com/fatih/color"
	"github.com/fsnotify/fsnotify"
	"log"
	"os"
	"path"
	"path/filepath"
)

const (
	configTmpl = "// Code generated by lazyGo. DO NOT EDIT.\n\npackage config\n\n"

	configPath = "./config"
	configName = "settings.yaml"

	configGoPath = "./internal/config"
	configGoName = "options.go"
)

// Sync Auto-sync configuration
func Sync() error {
	//check if the project is valid
	var (
		configAbsPath string
		err           error
	)

	configAbsPath, err = filepath.Abs(configPath)
	if err != nil {
		return err
	}

	if !util.IsFolderExist(configAbsPath) {
		return errorx.SDKConfigFolderNotExist
	}

	return generateConfigStruct()
}

// Watch listening for config changes and auto-sync.
func Watch() (*fstask.FsTask, error) {
	var (
		configAbsPath string
		fsTask        *fstask.FsTask
		err           error
	)

	configAbsPath, err = filepath.Abs(configPath)
	if err != nil {
		return nil, err
	}

	if !util.IsFolderExist(configAbsPath) {
		return nil, errorx.SDKConfigFolderNotExist
	}

	fsTask, err = fstask.New(configAbsPath)
	if err != nil {
		return nil, err
	}

	if err = fsTask.Add(fstask.Task{
		Rule:   ".*settings.yaml",
		Action: []string{"create", "write"},
		Handle: func(event fsnotify.Event) {
			if err = generateConfigStruct(); err != nil {
				color.Blue("%v: %v", errorx.SDKConfigWatchFailed, err)
				return
			}
			log.Println("config update success")
		},
	}); err != nil {
		return nil, err
	}

	return fsTask, nil
}

func generateConfigStruct() error {
	var (
		configFileAbsPath, configGoAbsPath, configGoFileAbsPath string
		configContent, structContent                            []byte
		file                                                    *os.File
		err                                                     error
	)

	configFileAbsPath, err = filepath.Abs(path.Join(configPath, configName))
	if err != nil {
		return err
	}

	if !util.IsFileExist(configFileAbsPath) {
		return nil
	}

	configGoAbsPath, err = filepath.Abs(configGoPath)
	if err != nil {
		return err
	}

	if err = util.MkdirIfNotExist(configGoAbsPath); err != nil {
		return err
	}

	configGoFileAbsPath, err = filepath.Abs(path.Join(configGoPath, configGoName))
	if err != nil {
		return err
	}

	configContent, err = os.ReadFile(configFileAbsPath)
	if err != nil {
		return err
	}

	structContent, err = go2struct.YAML2Struct("options", configContent)
	if err != nil {
		return err
	}

	file, err = os.Create(configGoFileAbsPath)
	if err != nil {
		return err
	}
	defer file.Close()

	if _, err = file.WriteString(configTmpl + string(structContent)); err != nil {
		return err
	}

	return nil
}
